### ISSUE TITLE
How to reproduce the result of B0 10steps in CIFAR100.

### ISSUE THREAD

**Issue by HenryZ94264** [G-U-N/ECCV22-FOSTER#4]
Hi!

Thank you for the repo and the paper, 

I have run the origin FOSTER repo and get final top-1 CNN accuracy at about 60 in CIFAR100 while it's about 70 in the paper.

I was wondering about which part is wrong, could you tell me where the problem is?

It would be greatly appreciated for any help from you.

Here is the training log.
[cil_1993_foster_resnet32_cifar100_10_10_0.94_0.97_False_False.log](https://github.com/G-U-N/ECCV22-FOSTER/files/9522922/cil_1993_foster_resnet32_cifar100_10_10_0.94_0.97_False_False.log)

**Comment by G-U-N** [comment]
Hi, thanks for your interest. I have checked your training log.

First, you seem to misunderstand the concept of `average accuracy of all sessions` reported in our paper. It's the average accuracy of all sessions rather than the accuracy at the last session.  
Say you have got the result [93.5, 80.2, 77.1, 72.42, 69.44, 66.97, 65.74, 62.78, 60.96, 59.41], the `average accuracy of all sessions` is the mean value of the list (i.e., 70.85 as you reproduced). Check [this issue](https://github.com/G-U-N/PyCIL/issues/5) in [PyCIL](https://github.com/G-U-N/PyCIL) to understand it.

Second, when running on benchmarks with Base 0, you should set the  `fixed memory` to `false` in the config JSON file, which follows the prior works. This allows the model to allocate more exemplars in the early sessions. Refer to [PyCIL-issue-4](https://github.com/G-U-N/PyCIL/issues/4), [PyCIL-issue-2](https://github.com/G-U-N/PyCIL/issues/2) to understand it.  After doing so, you will get the ideal result.

Hope this can help you.

**Comment by HenryZ94264** [comment]
Thanks a lot! I'm having a better understanding of the setting now. 

So it's like when running on benchmarks with half of all the classes as base classes, say Base 50 in CIFAR100, the prior works fix the memory. But when running on Base 0, we should set it to false.
