### ISSUE TITLE
Question about the CIFAR dataset

### ISSUE THREAD

**Issue by HarborYuan** [G-U-N/ECCV22-FOSTER#5]
Hi @G-U-N ,

Thanks for your work on FOSTER.

I have a question about the evaluation protocol in the paper. In table 1, B50-10steps, the DER is with 66.36. But in their paper, they claim to have a 72.45 results in table 2 (CIFAR100-B50, 10 steps). Is the margin caused by the difference in the evaluation protocol?

**Comment by G-U-N** [comment]
Thank you so much for your interest in our work.

DER claims they use the standard resnet-18 rather than the modified resnet-32 for CIFAR-100, and the following is copied from the implementation details in the paper.

> We note that most previous works use a modified 32-layers ResNet, which has fewer channels and residual blocks compared to standard ResNet-32. We argue that such a small network is not suitable because it cannot achieve competitive results on CIFAR100 compared with standard 18-layers ResNet and may underestimate the performance of methods. We run these methods with standard ResNet-18 on the same class orders based on their code implementation.

They also report the performance on CIFAR-100 with the modified 32-layers ResNet in the appendices (table 7, 8), and you can refer to that for a fair comparison.   

Hope this clarifies your queries.

**Comment by HarborYuan** [comment]
Thanks for your help.
